services:
  - type: web
    name: parkisons_app
    env: docker
    region: oregon
    plan: free
    dockerfilePath: ./docker
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
